I'm sorry, but an uncaught exception occurred.

While running game code:
  File "script.rpy", line 1721, in script
    show Radio_Set_And_Cart_On_The_Ground_With_Border_01 with Diccolve( 0.2 )
  File "script.rpy", line 1721, in <module>
    show Radio_Set_And_Cart_On_The_Ground_With_Border_01 with Diccolve( 0.2 )
NameError: name 'Diccolve' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "script.rpy", line 1721, in script
    show Radio_Set_And_Cart_On_The_Ground_With_Border_01 with Diccolve( 0.2 )
  File "/home/daniel/Documents/Sources/renpy/renpy-7.3.2-sdk/renpy/ast.py", line 1383, in execute
    paired = renpy.python.py_eval(self.paired)
  File "/home/daniel/Documents/Sources/renpy/renpy-7.3.2-sdk/renpy/python.py", line 2035, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/daniel/Documents/Sources/renpy/renpy-7.3.2-sdk/renpy/python.py", line 2028, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "script.rpy", line 1721, in <module>
    show Radio_Set_And_Cart_On_The_Ground_With_Border_01 with Diccolve( 0.2 )
NameError: name 'Diccolve' is not defined

Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
Ren'Py 7.3.2.320
radiopulsarvn 1.0
Wed Feb 26 21:37:47 2020
